-- reference queries NOT answerable from our generated query set
-- 42 queries

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `mentions`,     `posts`,     `photos`,     `profiles` WHERE `profiles`.`person_id` = `posts`.`author_id` AND `posts`.`type` = 'StatusMessage' AND (`photos`.`status_message_guid` = `posts`.`guid` AND `posts`.`text` IS NULL) AND (`posts`.`id` = `mentions`.`mentions_container_id` AND `mentions`.`id` = `notifications`.`target_id` AND ('Notifications::MentionedInPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `people`.`id` AS `id2`, `people`.`guid` AS `guid0`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at1`, `people`.`updated_at` AS `updated_at1`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `posts`,     `mentions`,     `people` WHERE `people`.`id` = `mentions`.`person_id` AND (`posts`.`type` = 'StatusMessage' AND `mentions`.`mentions_container_id` = `notifications`.`target_id`) AND (`mentions`.`mentions_container_type` = 'Post' AND `posts`.`id` = `notifications`.`target_id` AND ('Notifications::CommentOnPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `posts`.`id` AS `id2`, `posts`.`author_id` AS `author_id0`, `posts`.`public`, `posts`.`guid` AS `guid0`, `posts`.`type` AS `type0`, `posts`.`text` AS `text0`, `posts`.`created_at` AS `created_at1`, `posts`.`updated_at` AS `updated_at1`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count` AS `likes_count0`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids` FROM `notifications`,     `mentions`,     `comments`,     `posts` WHERE `posts`.`id` = `comments`.`commentable_id` AND `comments`.`id` = `mentions`.`mentions_container_id` AND `mentions`.`id` = `notifications`.`target_id` AND 'Notifications::MentionedInComment' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `photos`.`id` AS `id2`, `photos`.`author_id` AS `author_id0`, `photos`.`public` AS `public0`, `photos`.`guid` AS `guid0`, `photos`.`pending`, `photos`.`text` AS `text0`, `photos`.`remote_photo_path`, `photos`.`remote_photo_name`, `photos`.`random_string`, `photos`.`processed_image`, `photos`.`created_at` AS `created_at1`, `photos`.`updated_at` AS `updated_at1`, `photos`.`unprocessed_image`, `photos`.`status_message_guid`, `photos`.`comments_count` AS `comments_count0`, `photos`.`height`, `photos`.`width` FROM `notifications`,     `mentions`,     `posts`,     `photos` WHERE `photos`.`status_message_guid` = `posts`.`guid` AND (`posts`.`type` = 'StatusMessage' AND `posts`.`text` IS NULL) AND (`posts`.`id` = `mentions`.`mentions_container_id` AND `mentions`.`id` = `notifications`.`target_id` AND ('Notifications::MentionedInPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `people`.`id` AS `id1`, `people`.`guid` AS `guid0`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at1`, `people`.`updated_at` AS `updated_at1`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `posts`,     `people` WHERE `people`.`id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::AlsoCommented' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `people`.`id` AS `id1`, `people`.`guid`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at1`, `people`.`updated_at` AS `updated_at1`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `notification_actors`,     `people` WHERE `people`.`id` = `notification_actors`.`person_id` AND `notification_actors`.`notification_id` = `notifications`.`id` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `people`.`id` AS `id1`, `people`.`guid` AS `guid0`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at1`, `people`.`updated_at` AS `updated_at1`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `posts`,     `people` WHERE `people`.`id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::CommentOnPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `contacts`,     `profiles` WHERE `profiles`.`person_id` = `notifications`.`target_id` AND `notifications`.`type` = 'Notifications::StartedSharing' AND `contacts`.`user_id` = _MY_UID AND `contacts`.`person_id` = `notifications`.`target_id` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `people`.`id` AS `id1`, `people`.`guid` AS `guid0`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at1`, `people`.`updated_at` AS `updated_at1`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `posts`,     `people` WHERE `people`.`id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::Reshared' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `notification_actors`,     `profiles` WHERE `profiles`.`person_id` = `notification_actors`.`person_id` AND `notification_actors`.`notification_id` = `notifications`.`id` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `people`.`id` AS `id1`, `people`.`guid` AS `guid0`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at1`, `people`.`updated_at` AS `updated_at1`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `posts`,     `people` WHERE `people`.`id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::Liked' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `posts`,     `profiles` WHERE `profiles`.`person_id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::AlsoCommented' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `posts`,     `profiles` WHERE `profiles`.`person_id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::CommentOnPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `comments`.`id` AS `id1`, `comments`.`text`, `comments`.`commentable_id`, `comments`.`author_id`, `comments`.`guid`, `comments`.`created_at` AS `created_at0`, `comments`.`updated_at` AS `updated_at0`, `comments`.`likes_count`, `comments`.`commentable_type` FROM `notifications`,     `mentions`,     `comments` WHERE `comments`.`id` = `mentions`.`mentions_container_id` AND `mentions`.`id` = `notifications`.`target_id` AND 'Notifications::MentionedInComment' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `blocks`.`id` AS `id1`, `blocks`.`user_id` AS `user_id0`, `blocks`.`person_id` AS `person_id0` FROM `notifications`,     `contacts`,     `blocks` WHERE `blocks`.`user_id` = _MY_UID AND (`blocks`.`person_id` = `notifications`.`target_id` AND `notifications`.`type` = 'Notifications::StartedSharing') AND (`contacts`.`user_id` = _MY_UID AND (`contacts`.`person_id` = `notifications`.`target_id` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `mentions`.`id` AS `id1`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type` FROM `notifications`,     `posts`,     `mentions` WHERE `mentions`.`mentions_container_id` = `notifications`.`target_id` AND (`mentions`.`mentions_container_type` = 'Post' AND `posts`.`type` = 'StatusMessage') AND (`posts`.`id` = `notifications`.`target_id` AND ('Notifications::CommentOnPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `posts`.`id` AS `id1`, `posts`.`author_id`, `posts`.`public`, `posts`.`guid`, `posts`.`type` AS `type0`, `posts`.`text`, `posts`.`created_at` AS `created_at0`, `posts`.`updated_at` AS `updated_at0`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids` FROM `notifications`,     `mentions`,     `posts` WHERE `posts`.`id` = `mentions`.`mentions_container_id` AND `mentions`.`id` = `notifications`.`target_id` AND 'Notifications::MentionedInPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `mentions`.`id` AS `id1`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type` FROM `notifications`,     `posts`,     `mentions` WHERE `mentions`.`mentions_container_id` = `notifications`.`target_id` AND (`mentions`.`mentions_container_type` = 'Post' AND `posts`.`type` = 'StatusMessage') AND (`posts`.`id` = `notifications`.`target_id` AND ('Notifications::Reshared' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `mentions`.`id` AS `id1`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type` FROM `notifications`,     `posts`,     `mentions` WHERE `mentions`.`mentions_container_id` = `notifications`.`target_id` AND (`mentions`.`mentions_container_type` = 'Post' AND `posts`.`type` = 'StatusMessage') AND (`posts`.`id` = `notifications`.`target_id` AND ('Notifications::AlsoCommented' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `posts`,     `profiles` WHERE `profiles`.`person_id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::Reshared' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `mentions`.`id` AS `id1`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type` FROM `notifications`,     `posts`,     `mentions` WHERE `mentions`.`mentions_container_id` = `notifications`.`target_id` AND (`mentions`.`mentions_container_type` = 'Post' AND `posts`.`type` = 'StatusMessage') AND (`posts`.`id` = `notifications`.`target_id` AND ('Notifications::Liked' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID));

SELECT `profiles`.`id` AS `id1`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`birthday`, `profiles`.`gender`, `profiles`.`bio`, `profiles`.`searchable`, `profiles`.`person_id` AS `person_id0`, `profiles`.`created_at` AS `created_at1`, `profiles`.`updated_at` AS `updated_at1`, `profiles`.`location`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `contacts`,     `profiles` WHERE `notifications`.`type` = 'Notifications::StartedSharing' AND (`profiles`.`public_details` = TRUE AND `profiles`.`person_id` = `notifications`.`target_id`) AND (`contacts`.`user_id` = _MY_UID AND `contacts`.`person_id` = `notifications`.`target_id` AND (`notifications`.`recipient_id` = _MY_UID AND `contacts`.`sharing` = FALSE));

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `notifications`,     `posts`,     `profiles` WHERE `profiles`.`person_id` = `posts`.`author_id` AND `posts`.`id` = `notifications`.`target_id` AND 'Notifications::Liked' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `conversation_visibilities`.`unread` FROM `people`,     `conversation_visibilities` WHERE `conversation_visibilities`.`person_id` = `people`.`id` AND `people`.`owner_id` = _MY_UID;

SELECT `notification_actors`.`id` AS `id0`, `notification_actors`.`notification_id`, `notification_actors`.`person_id`, `notification_actors`.`created_at` AS `created_at0`, `notification_actors`.`updated_at` AS `updated_at0` FROM `notifications`,     `notification_actors` WHERE `notification_actors`.`notification_id` = `notifications`.`id` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `posts`.`id` AS `id0`, `posts`.`author_id`, `posts`.`public`, `posts`.`guid`, `posts`.`type` AS `type0`, `posts`.`text`, `posts`.`created_at` AS `created_at0`, `posts`.`updated_at` AS `updated_at0`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids` FROM `notifications`,     `posts` WHERE `posts`.`id` = `notifications`.`target_id` AND 'Notifications::Liked' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT 1 AS `one` FROM `people`,     `roles` WHERE `roles`.`name` IN ('admin', 'moderator') AND `roles`.`person_id` = `people`.`id` AND `people`.`owner_id` = _MY_UID;

SELECT 1 AS `one` FROM `people`,     `roles` WHERE `roles`.`person_id` = `people`.`id` AND `roles`.`name` = 'admin' AND `people`.`owner_id` = _MY_UID;

SELECT `posts`.`id` AS `id0`, `posts`.`author_id`, `posts`.`public`, `posts`.`guid`, `posts`.`type` AS `type0`, `posts`.`text`, `posts`.`created_at` AS `created_at0`, `posts`.`updated_at` AS `updated_at0`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids` FROM `notifications`,     `posts` WHERE `posts`.`id` = `notifications`.`target_id` AND 'Notifications::CommentOnPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details` FROM `people`,     `profiles` WHERE `profiles`.`person_id` = `people`.`id` AND `people`.`owner_id` = _MY_UID;

SELECT `people`.`id` AS `id0`, `people`.`guid`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at0`, `people`.`updated_at` AS `updated_at0`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `people` WHERE `people`.`id` = `notifications`.`target_id` AND `notifications`.`type` = 'Notifications::StartedSharing' AND `notifications`.`recipient_id` = _MY_UID;

SELECT `contacts`.`id` AS `id0`, `contacts`.`user_id`, `contacts`.`person_id`, `contacts`.`created_at` AS `created_at0`, `contacts`.`updated_at` AS `updated_at0`, `contacts`.`sharing`, `contacts`.`receiving` FROM `notifications`,     `contacts` WHERE `contacts`.`user_id` = _MY_UID AND `contacts`.`person_id` = `notifications`.`target_id` AND `notifications`.`type` = 'Notifications::StartedSharing' AND `notifications`.`recipient_id` = _MY_UID;

SELECT `mentions`.`id` AS `id0`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type` FROM `notifications`,     `mentions` WHERE `mentions`.`id` = `notifications`.`target_id` AND 'Notifications::MentionedInPost' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `people`.`id` AS `id0`, `people`.`guid`, `people`.`diaspora_handle`, `people`.`serialized_public_key`, `people`.`owner_id`, `people`.`created_at` AS `created_at0`, `people`.`updated_at` AS `updated_at0`, `people`.`closed_account`, `people`.`fetch_status`, `people`.`pod_id` FROM `notifications`,     `people` WHERE `people`.`id` = `notifications`.`target_id` AND 'Notifications::ContactsBirthday' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `mentions`.`id` AS `id0`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type` FROM `notifications`,     `mentions` WHERE `mentions`.`id` = `notifications`.`target_id` AND 'Notifications::MentionedInComment' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `posts`.`id` AS `id0`, `posts`.`author_id`, `posts`.`public`, `posts`.`guid`, `posts`.`type` AS `type0`, `posts`.`text`, `posts`.`created_at` AS `created_at0`, `posts`.`updated_at` AS `updated_at0`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids` FROM `notifications`,     `posts` WHERE `posts`.`id` = `notifications`.`target_id` AND 'Notifications::AlsoCommented' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT `posts`.`id` AS `id0`, `posts`.`author_id`, `posts`.`public`, `posts`.`guid`, `posts`.`type` AS `type0`, `posts`.`text`, `posts`.`created_at` AS `created_at0`, `posts`.`updated_at` AS `updated_at0`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids` FROM `notifications`,     `posts` WHERE `posts`.`id` = `notifications`.`target_id` AND 'Notifications::Reshared' = `notifications`.`type` AND `notifications`.`recipient_id` = _MY_UID;

SELECT * FROM `services` WHERE `user_id` = _MY_UID;

SELECT * FROM `people` WHERE `owner_id` = _MY_UID;

SELECT * FROM `contacts` WHERE `user_id` = _MY_UID AND `receiving` = TRUE;

SELECT * FROM `users` WHERE `id` = _MY_UID;

SELECT * FROM `aspects` WHERE `user_id` = _MY_UID;
