-- reference queries NOT answerable from our generated query set
-- 11 queries

SELECT `tags`.`name`, `taggings`.`id`, `people`.`guid` FROM `people`,     `profiles`,     `tags`,     `taggings` WHERE `tags`.`id` = `taggings`.`tag_id` AND (`taggings`.`taggable_id` = `profiles`.`id` AND `taggings`.`taggable_type` = 'Profile') AND (`taggings`.`context` = 'tags' AND (`profiles`.`person_id` = `people`.`id` AND `people`.`closed_account` = FALSE));

SELECT `tags`.`id`, `tags`.`name`, `tags`.`taggings_count`, `taggings`.`id` AS `id0`, `people`.`guid` FROM `people`,     `profiles`,     `tags`,     `taggings` WHERE `tags`.`id` = `taggings`.`tag_id` AND (`taggings`.`taggable_id` = `profiles`.`id` AND `taggings`.`taggable_type` = 'Profile') AND (`taggings`.`context` = 'tags' AND `profiles`.`public_details` = TRUE AND (`profiles`.`person_id` = `people`.`id` AND `people`.`closed_account` = FALSE));

SELECT `tags`.`id`, `tags`.`name`, `tags`.`taggings_count`, `taggings`.`id` AS `id0`, `people`.`guid` FROM `people`,     `profiles`,     `tags`,     `taggings` WHERE `tags`.`id` = `taggings`.`tag_id` AND (`taggings`.`taggable_id` = `profiles`.`id` AND `taggings`.`taggable_type` = 'Profile') AND (`taggings`.`context` = 'tags' AND `profiles`.`person_id` = `people`.`id` AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `photos`.`id`, `photos`.`author_id`, `photos`.`public`, `photos`.`guid`, `photos`.`pending`, `photos`.`text`, `photos`.`remote_photo_path`, `photos`.`remote_photo_name`, `photos`.`random_string`, `photos`.`processed_image`, `photos`.`created_at`, `photos`.`updated_at`, `photos`.`unprocessed_image`, `photos`.`status_message_guid`, `photos`.`comments_count`, `photos`.`height`, `photos`.`width`, `people`.`guid` FROM `people`,     `photos`,     `share_visibilities` WHERE `share_visibilities`.`shareable_id` = `photos`.`id` AND `share_visibilities`.`shareable_type` = 'Photo' AND (`photos`.`author_id` = `people`.`id` AND `share_visibilities`.`user_id` = _MY_UID) AND (`photos`.`created_at` < _NOW AND `people`.`owner_id` IS NULL AND (`photos`.`pending` = FALSE AND `people`.`closed_account` = FALSE));

SELECT 1 AS `one`, `people`.`guid` FROM `people`,     `people` AS `people0`,     `roles` WHERE `roles`.`person_id` = `people0`.`id` AND `roles`.`name` = 'admin' AND `people0`.`owner_id` = _MY_UID AND `people`.`closed_account` = FALSE;

SELECT `pods`.`id` AS `id0`, `pods`.`host`, `pods`.`ssl`, `pods`.`created_at` AS `created_at0`, `pods`.`updated_at` AS `updated_at0`, `pods`.`status`, `pods`.`checked_at`, `pods`.`offline_since`, `pods`.`response_time`, `pods`.`software`, `pods`.`error`, `pods`.`port`, `pods`.`blocked`, `pods`.`scheduled_check`, `people`.`guid` FROM `people`,     `pods` WHERE `pods`.`id` = `people`.`pod_id` AND `people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE;

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details`, `people`.`guid` FROM `people`,     `profiles` WHERE `profiles`.`person_id` = `people`.`id` AND `people`.`closed_account` = FALSE;

SELECT `profiles`.`id` AS `id0`, `profiles`.`diaspora_handle` AS `diaspora_handle0`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`birthday`, `profiles`.`gender`, `profiles`.`bio`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at` AS `created_at0`, `profiles`.`updated_at` AS `updated_at0`, `profiles`.`location`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details`, `people`.`guid` FROM `people`,     `profiles` WHERE `profiles`.`public_details` = TRUE AND `profiles`.`person_id` = `people`.`id` AND `people`.`closed_account` = FALSE;

SELECT `aspects`.`id` AS `id0`, `aspects`.`name`, `aspects`.`user_id`, `aspects`.`created_at` AS `created_at0`, `aspects`.`updated_at` AS `updated_at0`, `aspects`.`order_id`, `aspects`.`chat_enabled`, `aspects`.`post_default`, `people`.`guid` FROM `people`,     `aspects` WHERE `aspects`.`user_id` = _MY_UID AND `people`.`closed_account` = FALSE;

SELECT `photos`.`id` AS `id0`, `photos`.`author_id`, `photos`.`public`, `photos`.`guid` AS `guid0`, `photos`.`pending`, `photos`.`text`, `photos`.`remote_photo_path`, `photos`.`remote_photo_name`, `photos`.`random_string`, `photos`.`processed_image`, `photos`.`created_at` AS `created_at0`, `photos`.`updated_at` AS `updated_at0`, `photos`.`unprocessed_image`, `photos`.`status_message_guid`, `photos`.`comments_count`, `photos`.`height`, `photos`.`width`, `people`.`guid` FROM `people`,     `photos` WHERE `photos`.`author_id` = `people`.`id` AND `photos`.`created_at` < _NOW AND `people`.`owner_id` = _MY_UID AND `photos`.`pending` = FALSE AND `people`.`closed_account` = FALSE;

SELECT * FROM `users` WHERE `id` = _MY_UID;
