#!/usr/bin/python3
"""
Standalone concolic run for label: shopify_type_not_found

Generated by run_concolic.py — execute directly:
    python3 runs/run_shopify_type_not_found.py

The RunDump JSON includes this script source in the "script" field.
"""
import json
import os
import sys

sys.path.insert(0, '/home/dev/project/src')
sys.path.insert(0, '/home/dev/project/py_examples/chattermate/chattermate.chat/backend')

from py_runtime import CallInterceptor, SymbolicVar
from concolic_engine.run import Run

interceptor = CallInterceptor()


@interceptor.target(lambda a, n: 0)
def check_session_access(
    session_id: str, has_user_id: bool,
    has_user_groups: bool, include_unassigned: bool,
) -> bool:
    """Target for chat_repo.check_session_access()."""


@interceptor.target(lambda a, n: 1 if a.get("found") else 0)
def get_chat_detail(
    session_id: str, org_id: str,
    can_view_all: bool, found: bool,
) -> dict:
    """Target for chat_repo.get_chat_detail()."""


@interceptor.target
def source_get_chat_detail(
    session_id: str,
    auth_type: str,
    can_view_all: bool,
    can_view_assigned: bool,
    can_view_unassigned: bool,
    session_found: bool,
) -> str:
    if auth_type == "shopify_session" or auth_type == "shopify":
        result = get_chat_detail(session_id, "o1", True, session_found)
        if not result:
            return "shopify_404"
        return "shopify_found"
    if not can_view_all:
        has_access = check_session_access(
            session_id,
            has_user_id=can_view_assigned,
            has_user_groups=can_view_assigned,
            include_unassigned=can_view_unassigned,
        )
        if not has_access:
            return "jwt_403_not_found"
    result = get_chat_detail(session_id, "o1", can_view_all, session_found)
    if not result:
        return "jwt_404"
    return "jwt_found"


# --- Run ---
SymbolicVar.clear_path_conditions()
from py_runtime.symbolic_func import reset_symbolic_state
reset_symbolic_state()

kwargs = {
        "session_id": "shopify_type_not_found",
        "auth_type": "shopify",
        "can_view_all": True,
        "can_view_assigned": True,
        "can_view_unassigned": True,
        "session_found": False,
    }

# Embed this script's own source as the dump "script" field
_this_source = open(__file__).read()

dump = interceptor.run(
    source_get_chat_detail,
    kwargs,
    label='shopify_type_not_found',
    script=_this_source,
)

report_dir = '/home/dev/project/reports/chattermate-get-chat-detail'
dump_path = os.path.join(report_dir, 'dump_shopify_type_not_found.json')
with open(dump_path, "w") as f:
    json.dump(dump, f, indent=2)
print(f"Written: {dump_path}")
