-- reference queries NOT answerable from our generated query set
-- 16 queries

SELECT `poll_participations`.`id` AS `id3`, `poll_participations`.`poll_answer_id`, `poll_participations`.`author_id` AS `author_id0`, `poll_participations`.`poll_id`, `poll_participations`.`guid` AS `guid3`, `poll_participations`.`created_at` AS `created_at3`, `poll_participations`.`updated_at` AS `updated_at3`, `people`.`guid` FROM `people`,     `people` AS `people0`,     `posts`,     `share_visibilities`,     `polls`,     `poll_participations` WHERE `poll_participations`.`poll_id` = `polls`.`id` AND (`poll_participations`.`author_id` = `people0`.`id` AND `posts`.`type` = 'StatusMessage') AND (`polls`.`status_message_id` = `posts`.`id` AND (`share_visibilities`.`shareable_id` = `posts`.`id` AND `share_visibilities`.`shareable_type` = 'Post')) AND (`posts`.`author_id` = `people`.`id` AND (`share_visibilities`.`user_id` = _MY_UID AND `posts`.`created_at` < _NOW) AND (`people0`.`owner_id` = _MY_UID AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE)));

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details`, `people`.`guid` FROM `people`,     `posts`,     `share_visibilities`,     `comments`,     `profiles` WHERE `profiles`.`person_id` = `comments`.`author_id` AND (`comments`.`commentable_id` = `posts`.`id` AND `comments`.`commentable_type` = 'Post') AND (`posts`.`comments_count` <> 0 AND (`share_visibilities`.`shareable_id` = `posts`.`id` AND `share_visibilities`.`shareable_type` = 'Post')) AND (`posts`.`author_id` = `people`.`id` AND (`share_visibilities`.`user_id` = _MY_UID AND `posts`.`created_at` < _NOW) AND (`posts`.`type` IN ('Reshare', 'StatusMessage') AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE)));

SELECT `poll_answers`.`id` AS `id2`, `poll_answers`.`answer`, `poll_answers`.`poll_id`, `poll_answers`.`guid` AS `guid2`, `poll_answers`.`vote_count`, `people`.`guid` FROM `people`,     `posts`,     `polls`,     `poll_answers` WHERE `poll_answers`.`poll_id` = `polls`.`id` AND `posts`.`type` = 'StatusMessage' AND (`polls`.`status_message_id` = `posts`.`id` AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`public` = TRUE AND `posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `polls`.`id` AS `id1`, `polls`.`question`, `polls`.`status_message_id`, `polls`.`status`, `polls`.`guid` AS `guid1`, `polls`.`created_at` AS `created_at1`, `polls`.`updated_at` AS `updated_at1`, `people`.`guid` FROM `people`,     `posts`,     `share_visibilities`,     `polls` WHERE `polls`.`status_message_id` = `posts`.`id` AND `posts`.`type` = 'StatusMessage' AND (`share_visibilities`.`shareable_id` = `posts`.`id` AND `share_visibilities`.`shareable_type` = 'Post') AND (`posts`.`author_id` = `people`.`id` AND `share_visibilities`.`user_id` = _MY_UID AND (`posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE)));

SELECT `locations`.`id` AS `id1`, `locations`.`address`, `locations`.`lat`, `locations`.`lng`, `locations`.`status_message_id`, `locations`.`created_at` AS `created_at1`, `locations`.`updated_at` AS `updated_at1`, `people`.`guid` FROM `people`,     `posts`,     `share_visibilities`,     `locations` WHERE `locations`.`status_message_id` = `posts`.`id` AND `posts`.`type` = 'StatusMessage' AND (`share_visibilities`.`shareable_id` = `posts`.`id` AND `share_visibilities`.`shareable_type` = 'Post') AND (`posts`.`author_id` = `people`.`id` AND `share_visibilities`.`user_id` = _MY_UID AND (`posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE)));

SELECT `mentions`.`id` AS `id1`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type`, `people`.`guid` FROM `people`,     `posts`,     `share_visibilities`,     `mentions` WHERE `mentions`.`mentions_container_id` = `posts`.`id` AND `mentions`.`mentions_container_type` = 'Post' AND (`posts`.`type` = 'StatusMessage' AND (`share_visibilities`.`shareable_id` = `posts`.`id` AND `share_visibilities`.`shareable_type` = 'Post')) AND (`posts`.`author_id` = `people`.`id` AND `share_visibilities`.`user_id` = _MY_UID AND (`posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE)));

SELECT `open_graph_caches`.`id` AS `id1`, `open_graph_caches`.`title`, `open_graph_caches`.`ob_type`, `open_graph_caches`.`image`, `open_graph_caches`.`url`, `open_graph_caches`.`description`, `open_graph_caches`.`video_url`, `people`.`guid` FROM `people`,     `posts`,     `open_graph_caches` WHERE `open_graph_caches`.`id` = `posts`.`open_graph_cache_id` AND (`posts`.`author_id` = `people`.`id` AND `posts`.`public` = TRUE) AND (`posts`.`created_at` < _NOW AND `posts`.`type` IN ('Reshare', 'StatusMessage') AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `locations`.`id` AS `id1`, `locations`.`address`, `locations`.`lat`, `locations`.`lng`, `locations`.`status_message_id`, `locations`.`created_at` AS `created_at1`, `locations`.`updated_at` AS `updated_at1`, `people`.`guid` FROM `people`,     `posts`,     `locations` WHERE `locations`.`status_message_id` = `posts`.`id` AND (`posts`.`type` = 'StatusMessage' AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`created_at` < _NOW AND (`people`.`owner_id` = _MY_UID AND `people`.`closed_account` = FALSE));

SELECT `posts`.`id` AS `id0`, `posts`.`author_id`, `posts`.`public`, `posts`.`guid` AS `guid0`, `posts`.`type`, `posts`.`text`, `posts`.`created_at` AS `created_at0`, `posts`.`updated_at` AS `updated_at0`, `posts`.`provider_display_name`, `posts`.`root_guid`, `posts`.`likes_count`, `posts`.`comments_count`, `posts`.`o_embed_cache_id`, `posts`.`reshares_count`, `posts`.`interacted_at`, `posts`.`tweet_id`, `posts`.`open_graph_cache_id`, `posts`.`tumblr_ids`, `people`.`guid` FROM `people`,     `posts`,     `photos` WHERE `posts`.`type` = 'StatusMessage' AND (`photos`.`status_message_guid` = `posts`.`guid` AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`public` = TRUE AND `posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `photos`.`id` AS `id1`, `photos`.`author_id` AS `author_id0`, `photos`.`public` AS `public0`, `photos`.`guid` AS `guid1`, `photos`.`pending`, `photos`.`text` AS `text0`, `photos`.`remote_photo_path`, `photos`.`remote_photo_name`, `photos`.`random_string`, `photos`.`processed_image`, `photos`.`created_at` AS `created_at1`, `photos`.`updated_at` AS `updated_at1`, `photos`.`unprocessed_image`, `photos`.`status_message_guid`, `photos`.`comments_count` AS `comments_count0`, `photos`.`height`, `photos`.`width`, `people`.`guid` FROM `people`,     `posts`,     `photos` WHERE `photos`.`status_message_guid` = `posts`.`guid` AND (`posts`.`type` = 'StatusMessage' AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`public` = TRUE AND `posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `polls`.`id` AS `id1`, `polls`.`question`, `polls`.`status_message_id`, `polls`.`status`, `polls`.`guid` AS `guid1`, `polls`.`created_at` AS `created_at1`, `polls`.`updated_at` AS `updated_at1`, `people`.`guid` FROM `people`,     `posts`,     `polls` WHERE `polls`.`status_message_id` = `posts`.`id` AND (`posts`.`type` = 'StatusMessage' AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`created_at` < _NOW AND (`people`.`owner_id` = _MY_UID AND `people`.`closed_account` = FALSE));

SELECT `profiles`.`id`, `profiles`.`diaspora_handle`, `profiles`.`first_name`, `profiles`.`last_name`, `profiles`.`image_url`, `profiles`.`image_url_small`, `profiles`.`image_url_medium`, `profiles`.`searchable`, `profiles`.`person_id`, `profiles`.`created_at`, `profiles`.`updated_at`, `profiles`.`full_name`, `profiles`.`nsfw`, `profiles`.`public_details`, `people`.`guid` FROM `people`,     `posts`,     `profiles` WHERE `profiles`.`person_id` = `people`.`id` AND (`posts`.`author_id` = `people`.`id` AND `posts`.`public` = TRUE) AND (`posts`.`created_at` < _NOW AND `posts`.`type` IN ('Reshare', 'StatusMessage') AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `polls`.`id` AS `id1`, `polls`.`question`, `polls`.`status_message_id`, `polls`.`status`, `polls`.`guid` AS `guid1`, `polls`.`created_at` AS `created_at1`, `polls`.`updated_at` AS `updated_at1`, `people`.`guid` FROM `people`,     `posts`,     `polls` WHERE `polls`.`status_message_id` = `posts`.`id` AND (`posts`.`type` = 'StatusMessage' AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`public` = TRUE AND `posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `locations`.`id` AS `id1`, `locations`.`address`, `locations`.`lat`, `locations`.`lng`, `locations`.`status_message_id`, `locations`.`created_at` AS `created_at1`, `locations`.`updated_at` AS `updated_at1`, `people`.`guid` FROM `people`,     `posts`,     `locations` WHERE `locations`.`status_message_id` = `posts`.`id` AND (`posts`.`type` = 'StatusMessage' AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`public` = TRUE AND `posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT `mentions`.`id` AS `id1`, `mentions`.`mentions_container_id`, `mentions`.`person_id`, `mentions`.`mentions_container_type`, `people`.`guid` FROM `people`,     `posts`,     `mentions` WHERE `mentions`.`mentions_container_id` = `posts`.`id` AND `mentions`.`mentions_container_type` = 'Post' AND (`posts`.`type` = 'StatusMessage' AND `posts`.`author_id` = `people`.`id`) AND (`posts`.`public` = TRUE AND `posts`.`created_at` < _NOW AND (`people`.`owner_id` IS NULL AND `people`.`closed_account` = FALSE));

SELECT * FROM `users` WHERE `id` = _MY_UID;
