-- Auto-generated by gen_ddl.py from diaspora-schema.rb. Do not edit by hand.
CREATE TABLE "account_deletions" (
  "id" INT NOT NULL PRIMARY KEY,
  "person_id" INT,
  "completed_at" TIMESTAMP
);
CREATE TABLE "account_migrations" (
  "id" INT NOT NULL PRIMARY KEY,
  "old_person_id" INT NOT NULL,
  "new_person_id" INT NOT NULL,
  "completed_at" TIMESTAMP
);
CREATE TABLE "aspect_memberships" (
  "id" INT NOT NULL PRIMARY KEY,
  "aspect_id" INT NOT NULL,
  "contact_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "aspect_visibilities" (
  "id" INT NOT NULL PRIMARY KEY,
  "shareable_id" INT NOT NULL,
  "aspect_id" INT NOT NULL,
  "shareable_type" VARCHAR(255) NOT NULL
);
CREATE TABLE "aspects" (
  "id" INT NOT NULL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "user_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "order_id" INT,
  "chat_enabled" BOOLEAN,
  "post_default" BOOLEAN
);
CREATE TABLE "authorizations" (
  "id" INT NOT NULL PRIMARY KEY,
  "user_id" INT,
  "o_auth_application_id" INT,
  "refresh_token" VARCHAR(255),
  "code" VARCHAR(255),
  "redirect_uri" VARCHAR(255),
  "nonce" VARCHAR(255),
  "scopes" VARCHAR(255),
  "code_used" BOOLEAN,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "blocks" (
  "id" INT NOT NULL PRIMARY KEY,
  "user_id" INT,
  "person_id" INT
);
CREATE TABLE "chat_contacts" (
  "id" INT NOT NULL PRIMARY KEY,
  "user_id" INT NOT NULL,
  "jid" VARCHAR(255) NOT NULL,
  "name" VARCHAR(255),
  "ask" VARCHAR(255),
  "subscription" VARCHAR(255) NOT NULL
);
CREATE TABLE "chat_fragments" (
  "id" INT NOT NULL PRIMARY KEY,
  "user_id" INT NOT NULL,
  "root" VARCHAR(255) NOT NULL,
  "namespace" VARCHAR(255) NOT NULL,
  "xml" VARCHAR(65535) NOT NULL
);
CREATE TABLE "chat_offline_messages" (
  "id" INT NOT NULL PRIMARY KEY,
  "from" VARCHAR(255) NOT NULL,
  "to" VARCHAR(255) NOT NULL,
  "message" VARCHAR(65535) NOT NULL,
  "created_at" TIMESTAMP NOT NULL
);
CREATE TABLE "comment_signatures" (
  "id" INT NOT NULL PRIMARY KEY,
  "comment_id" INT NOT NULL,
  "author_signature" VARCHAR(65535) NOT NULL,
  "signature_order_id" INT NOT NULL,
  "additional_data" VARCHAR(65535)
);
CREATE TABLE "comments" (
  "id" INT NOT NULL PRIMARY KEY,
  "text" VARCHAR(65535) NOT NULL,
  "commentable_id" INT NOT NULL,
  "author_id" INT NOT NULL,
  "guid" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "likes_count" INT NOT NULL,
  "commentable_type" VARCHAR(255) NOT NULL
);
CREATE TABLE "contacts" (
  "id" INT NOT NULL PRIMARY KEY,
  "user_id" INT NOT NULL,
  "person_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "sharing" BOOLEAN NOT NULL,
  "receiving" BOOLEAN NOT NULL
);
CREATE TABLE "conversation_visibilities" (
  "id" INT NOT NULL PRIMARY KEY,
  "conversation_id" INT NOT NULL,
  "person_id" INT NOT NULL,
  "unread" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "conversations" (
  "id" INT NOT NULL PRIMARY KEY,
  "subject" VARCHAR(255),
  "guid" VARCHAR(255) NOT NULL,
  "author_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "invitation_codes" (
  "id" INT NOT NULL PRIMARY KEY,
  "token" VARCHAR(255),
  "user_id" INT,
  "count" INT,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "like_signatures" (
  "id" INT NOT NULL PRIMARY KEY,
  "like_id" INT NOT NULL,
  "author_signature" VARCHAR(65535) NOT NULL,
  "signature_order_id" INT NOT NULL,
  "additional_data" VARCHAR(65535)
);
CREATE TABLE "likes" (
  "id" INT NOT NULL PRIMARY KEY,
  "positive" BOOLEAN,
  "target_id" INT,
  "author_id" INT,
  "guid" VARCHAR(255),
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "target_type" VARCHAR(255) NOT NULL
);
CREATE TABLE "locations" (
  "id" INT NOT NULL PRIMARY KEY,
  "address" VARCHAR(255),
  "lat" VARCHAR(255),
  "lng" VARCHAR(255),
  "status_message_id" INT,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "mentions" (
  "id" INT NOT NULL PRIMARY KEY,
  "mentions_container_id" INT NOT NULL,
  "person_id" INT NOT NULL,
  "mentions_container_type" VARCHAR(255) NOT NULL
);
CREATE TABLE "messages" (
  "id" INT NOT NULL PRIMARY KEY,
  "conversation_id" INT NOT NULL,
  "author_id" INT NOT NULL,
  "guid" VARCHAR(255) NOT NULL,
  "text" VARCHAR(65535) NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "notification_actors" (
  "id" INT NOT NULL PRIMARY KEY,
  "notification_id" INT,
  "person_id" INT,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "notifications" (
  "id" INT NOT NULL PRIMARY KEY,
  "target_type" VARCHAR(255),
  "target_id" INT,
  "recipient_id" INT NOT NULL,
  "unread" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "type" VARCHAR(255)
);
CREATE TABLE "o_auth_access_tokens" (
  "id" INT NOT NULL PRIMARY KEY,
  "authorization_id" INT,
  "token" VARCHAR(255),
  "expires_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "o_auth_applications" (
  "id" INT NOT NULL PRIMARY KEY,
  "user_id" INT,
  "client_id" VARCHAR(255),
  "client_secret" VARCHAR(255),
  "client_name" VARCHAR(255),
  "redirect_uris" VARCHAR(65535),
  "response_types" VARCHAR(255),
  "grant_types" VARCHAR(255),
  "application_type" VARCHAR(255),
  "contacts" VARCHAR(255),
  "logo_uri" VARCHAR(255),
  "client_uri" VARCHAR(255),
  "policy_uri" VARCHAR(255),
  "tos_uri" VARCHAR(255),
  "sector_identifier_uri" VARCHAR(255),
  "token_endpoint_auth_method" VARCHAR(255),
  "jwks" VARCHAR(65535),
  "jwks_uri" VARCHAR(255),
  "ppid" BOOLEAN,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "o_embed_caches" (
  "id" INT NOT NULL PRIMARY KEY,
  "url" VARCHAR(255) NOT NULL,
  "data" VARCHAR(65535) NOT NULL
);
CREATE TABLE "open_graph_caches" (
  "id" INT NOT NULL PRIMARY KEY,
  "title" VARCHAR(255),
  "ob_type" VARCHAR(255),
  "image" VARCHAR(65535),
  "url" VARCHAR(65535),
  "description" VARCHAR(65535),
  "video_url" VARCHAR(65535)
);
CREATE TABLE "participations" (
  "id" INT NOT NULL PRIMARY KEY,
  "guid" VARCHAR(255),
  "target_id" INT,
  "target_type" VARCHAR(255) NOT NULL,
  "author_id" INT,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "count" INT NOT NULL
);
CREATE TABLE "people" (
  "id" INT NOT NULL PRIMARY KEY,
  "guid" VARCHAR(255) NOT NULL,
  "diaspora_handle" VARCHAR(255) NOT NULL,
  "serialized_public_key" VARCHAR(65535) NOT NULL,
  "owner_id" INT,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "closed_account" BOOLEAN,
  "fetch_status" INT,
  "pod_id" INT
);
CREATE TABLE "photos" (
  "id" INT NOT NULL PRIMARY KEY,
  "author_id" INT NOT NULL,
  "public" BOOLEAN NOT NULL,
  "guid" VARCHAR(255) NOT NULL,
  "pending" BOOLEAN NOT NULL,
  "text" VARCHAR(65535),
  "remote_photo_path" VARCHAR(65535),
  "remote_photo_name" VARCHAR(255),
  "random_string" VARCHAR(255),
  "processed_image" VARCHAR(255),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "unprocessed_image" VARCHAR(255),
  "status_message_guid" VARCHAR(255),
  "comments_count" INT,
  "height" INT,
  "width" INT
);
CREATE TABLE "pods" (
  "id" INT NOT NULL PRIMARY KEY,
  "host" VARCHAR(255) NOT NULL,
  "ssl" BOOLEAN,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "status" INT,
  "checked_at" TIMESTAMP,
  "offline_since" TIMESTAMP,
  "response_time" INT,
  "software" VARCHAR(255),
  "error" VARCHAR(255),
  "port" INT,
  "blocked" BOOLEAN,
  "scheduled_check" BOOLEAN NOT NULL
);
CREATE TABLE "poll_answers" (
  "id" INT NOT NULL PRIMARY KEY,
  "answer" VARCHAR(255) NOT NULL,
  "poll_id" INT NOT NULL,
  "guid" VARCHAR(255),
  "vote_count" INT
);
CREATE TABLE "poll_participation_signatures" (
  "id" INT NOT NULL PRIMARY KEY,
  "poll_participation_id" INT NOT NULL,
  "author_signature" VARCHAR(65535) NOT NULL,
  "signature_order_id" INT NOT NULL,
  "additional_data" VARCHAR(65535)
);
CREATE TABLE "poll_participations" (
  "id" INT NOT NULL PRIMARY KEY,
  "poll_answer_id" INT NOT NULL,
  "author_id" INT NOT NULL,
  "poll_id" INT NOT NULL,
  "guid" VARCHAR(255),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP
);
CREATE TABLE "polls" (
  "id" INT NOT NULL PRIMARY KEY,
  "question" VARCHAR(255) NOT NULL,
  "status_message_id" INT NOT NULL,
  "status" BOOLEAN,
  "guid" VARCHAR(255),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP
);
CREATE TABLE "posts" (
  "id" INT NOT NULL PRIMARY KEY,
  "author_id" INT NOT NULL,
  "public" BOOLEAN NOT NULL,
  "guid" VARCHAR(255) NOT NULL,
  "type" VARCHAR(255) NOT NULL,
  "text" VARCHAR(65535),
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "provider_display_name" VARCHAR(255),
  "root_guid" VARCHAR(255),
  "likes_count" INT,
  "comments_count" INT,
  "o_embed_cache_id" INT,
  "reshares_count" INT,
  "interacted_at" TIMESTAMP,
  "tweet_id" VARCHAR(255),
  "open_graph_cache_id" INT,
  "tumblr_ids" VARCHAR(65535)
);
CREATE TABLE "ppid" (
  "id" INT NOT NULL PRIMARY KEY,
  "o_auth_application_id" INT,
  "user_id" INT,
  "guid" VARCHAR(255),
  "identifier" VARCHAR(255)
);
CREATE TABLE "profiles" (
  "id" INT NOT NULL PRIMARY KEY,
  "diaspora_handle" VARCHAR(255),
  "first_name" VARCHAR(255),
  "last_name" VARCHAR(255),
  "image_url" VARCHAR(255),
  "image_url_small" VARCHAR(255),
  "image_url_medium" VARCHAR(255),
  "birthday" TIMESTAMP,
  "gender" VARCHAR(255),
  "bio" VARCHAR(65535),
  "searchable" BOOLEAN NOT NULL,
  "person_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "location" VARCHAR(255),
  "full_name" VARCHAR(255),
  "nsfw" BOOLEAN,
  "public_details" BOOLEAN
);
CREATE TABLE "references" (
  "id" INT NOT NULL PRIMARY KEY,
  "source_id" INT NOT NULL,
  "source_type" VARCHAR(255) NOT NULL,
  "target_id" INT NOT NULL,
  "target_type" VARCHAR(255) NOT NULL
);
CREATE TABLE "reports" (
  "id" INT NOT NULL PRIMARY KEY,
  "item_id" INT NOT NULL,
  "item_type" VARCHAR(255) NOT NULL,
  "reviewed" BOOLEAN,
  "text" VARCHAR(65535),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "user_id" INT NOT NULL
);
CREATE TABLE "roles" (
  "id" INT NOT NULL PRIMARY KEY,
  "person_id" INT,
  "name" VARCHAR(255),
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "services" (
  "id" INT NOT NULL PRIMARY KEY,
  "type" VARCHAR(255) NOT NULL,
  "user_id" INT NOT NULL,
  "uid" VARCHAR(255),
  "access_token" VARCHAR(255),
  "access_secret" VARCHAR(255),
  "nickname" VARCHAR(255),
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "share_visibilities" (
  "id" INT NOT NULL PRIMARY KEY,
  "shareable_id" INT NOT NULL,
  "hidden" BOOLEAN NOT NULL,
  "shareable_type" VARCHAR(255) NOT NULL,
  "user_id" INT NOT NULL
);
CREATE TABLE "signature_orders" (
  "id" INT NOT NULL PRIMARY KEY,
  "order" VARCHAR(255) NOT NULL
);
CREATE TABLE "simple_captcha_data" (
  "id" INT NOT NULL PRIMARY KEY,
  "key" VARCHAR(255),
  "value" VARCHAR(255),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP
);
CREATE TABLE "tag_followings" (
  "id" INT NOT NULL PRIMARY KEY,
  "tag_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "taggings" (
  "id" INT NOT NULL PRIMARY KEY,
  "tag_id" INT,
  "taggable_id" INT,
  "taggable_type" VARCHAR(255),
  "tagger_id" INT,
  "tagger_type" VARCHAR(255),
  "context" VARCHAR(255),
  "created_at" TIMESTAMP
);
CREATE TABLE "tags" (
  "id" INT NOT NULL PRIMARY KEY,
  "name" VARCHAR(255),
  "taggings_count" INT
);
CREATE TABLE "user_preferences" (
  "id" INT NOT NULL PRIMARY KEY,
  "email_type" VARCHAR(255),
  "user_id" INT,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL
);
CREATE TABLE "users" (
  "id" INT NOT NULL PRIMARY KEY,
  "username" VARCHAR(255) NOT NULL,
  "serialized_private_key" VARCHAR(65535),
  "getting_started" BOOLEAN NOT NULL,
  "disable_mail" BOOLEAN NOT NULL,
  "language" VARCHAR(255),
  "email" VARCHAR(255) NOT NULL,
  "encrypted_password" VARCHAR(255) NOT NULL,
  "reset_password_token" VARCHAR(255),
  "remember_created_at" TIMESTAMP,
  "sign_in_count" INT,
  "current_sign_in_at" TIMESTAMP,
  "last_sign_in_at" TIMESTAMP,
  "current_sign_in_ip" VARCHAR(255),
  "last_sign_in_ip" VARCHAR(255),
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "invited_by_id" INT,
  "authentication_token" VARCHAR(255),
  "unconfirmed_email" VARCHAR(255),
  "confirm_email_token" VARCHAR(255),
  "locked_at" TIMESTAMP,
  "show_community_spotlight_in_stream" BOOLEAN NOT NULL,
  "auto_follow_back" BOOLEAN,
  "auto_follow_back_aspect_id" INT,
  "hidden_shareables" VARCHAR(65535),
  "reset_password_sent_at" TIMESTAMP,
  "last_seen" TIMESTAMP,
  "remove_after" TIMESTAMP,
  "export" VARCHAR(255),
  "exported_at" TIMESTAMP,
  "exporting" BOOLEAN,
  "strip_exif" BOOLEAN,
  "exported_photos_file" VARCHAR(255),
  "exported_photos_at" TIMESTAMP,
  "exporting_photos" BOOLEAN,
  "color_theme" VARCHAR(255),
  "post_default_public" BOOLEAN,
  "consumed_timestep" INT,
  "otp_required_for_login" BOOLEAN,
  "otp_backup_codes" VARCHAR(65535),
  "plain_otp_secret" VARCHAR(255)
);
